cliffe/SecGen

config/scenario.xml, lib/helpers/vulnerability_helper.rb, lib/helpers/vulnerability_processor.rb, lib/objects/vulnerability.rb, lib/systemreader.rb, modules/vulnerabilities/unix/ftp/vsftpd_234_backdoor/secgen_metadata.xml, modules/vulnerabilities/unix/misc/distcc_exec/secgen_metadata.xml
made a few changes:
* scenario.xml's vulnerability tag now only requires the attributes the user wants to filter by. Previously we required empty strings for the attributes that were not being used but this is no longer the case. e.g. `<vulnerability access="remote">`  
* added cvss scores and some logic to select by rating (none, low, medium, high, critical)
* added capability for users to filter by CVSS Vector String. The search is flexible and the user can specify any segment pair (or pairs) they require. e.g. `<vulnerability vector_string="AV:N/AC:L">` for a vulnerability with a **N**etwork **A**ttack **V**ector and **L**ow **A**ccess **C**omplexity.
cheers
=> SG-12: add to secgen_metadata and make filterable from scenario.xml

lib/templates/vagrantbase.erb
Removes to make main repo working - mechanism for selecting a site hasnt been started yet.
=> removes wordpress in vagrantbase

lib/helpers/gem_exec.rb, modules/vulnerabilities/unix/nfs/nfs_overshare/manifests/config.pp, modules/vulnerabilities/unix/nfs/nfs_overshare/nfs_overshare.pp
Added a chomp to gem_exec's path evaluation, was leaving a trailing newline + evaluating /usr/bin/vagrant\n as false when the /usr/bin/vagrant file existed.
=> post-update fixes

modules/services/unix/update/unix_update/manifests/unix.pp, modules/services/unix/update/unix_update/secgen_metadata.xml, modules/services/unix/update/unix_update/unix_update.pp, modules/services/windows/update/windows_update/CHANGELOG.md, modules/services/windows/update/windows_update/CONTRIBUTING.md, modules/services/windows/update/windows_update/Gemfile, modules/services/windows/update/windows_update/Guardfile, modules/services/windows/update/windows_update/LICENSE, modules/services/windows/update/windows_update/README.md, modules/services/windows/update/windows_update/Rakefile, modules/services/windows/update/windows_update/checksums.json, modules/services/windows/update/windows_update/manifests/init.pp, modules/services/windows/update/windows_update/manifests/params.pp, modules/services/windows/update/windows_update/metadata.json, modules/services/windows/update/windows_update/secgen_metadata.xml, modules/services/windows/update/windows_update/spec/acceptance/nodesets/windows-2008R2-serverstandard-x64.yml, modules/services/windows/update/windows_update/spec/classes/coverage_spec.rb, modules/services/windows/update/windows_update/spec/classes/windows_autoupdate_spec.rb, modules/services/windows/update/windows_update/spec/spec.opts, modules/services/windows/update/windows_update/spec/spec_helper.rb, modules/services/windows/update/windows_update/spec/spec_helper_acceptance.rb, modules/services/windows/update/windows_update/windows_update.pp, scenarios/simple_examples/clean_system_with_update_unix.xml
Should make sure that newest software can be gotten off of the systems repositories. Also should be machine independent other then selecting whether windows or unix. Commands in the unix_update module need to be modified for different systems to be absolute paths. Added windows services directory and included a puppetforge module to control auto-updates within windows (currently disables auto-updates for windows systems).
Changes:
Added puppetforge windows module https://forge.puppet.com/puppet/windows_autoupdate/readme.
Added Debian repository updater.
Added secgen_metadata for both modules (unix_update and windows_update)
Added custom scenario clean_system_with_update_unix.xml which creates a clean system with just the update (can be used for testing)
=> Update service that performs the repository update for the created vm.

lib/schemas/vulnerability_metadata_schema.xsd
Add the Apache v2 licence to the vulnerabilities schema.
=> Apache v2 licence for vulnerabilities

secgen.rb
Changes output of build_config to output correct information about networks, was previously displaying all_available_services count instead of all_available_networks
=> Module loader bug fix

lib/helpers/constants.rb, lib/objects/module.rb, lib/objects/system.rb, lib/readers/module_reader.rb, lib/readers/system_reader.rb, lib/schemas/base_metadata_schema.xsd, lib/schemas/service_metadata_schema.xsd, lib/schemas/vulnerability_metadata_schema.xsd, modules/services/unix/http/apache/secgen_metadata.xml, modules/services/unix/update/unix_update/secgen_metadata.xml, modules/services/windows/update/windows_update/secgen_metadata.xml, modules/vulnerabilities/unix/local/writeable_shadow/secgen_metadata.xml, scenarios/default_scenario.xml, secgen.rb
Any module can include in secgen_metadata.xml \<requires> tags to require other modules that satisfy a set of conditions are also in the scenario. When selecting a module, each dependency is resolved by checking if a module already satisfies the condition, in which case nothing happens, or a module that satisfies all the conditions is randomly selected and added to the scenario. This is recursive so a module can require modules that require modules. 
When conflicts occur (say for example, a previously selected module conflicts with all the valid options for resolving a dependency) the scenario is regenerated. This bruteforce approach is fairly effective, but \<conflict> tags should be avoided wherever possible because they add complexity and reduce randomisation possibilities.
A module …
=> Module dependencies

modules/services/unix/file_share/samba/samba.pp
Merge of legacy code into Cliffe/master left module broken due to old Exec['update'] code.
Removed all legacy and non samba related code.
Only installs samba.
Tested and seems to be working.
=> Fix for the samba service module

lib/schemas/vulnerability_metadata_schema.xsd, modules/services/unix/http/apache_bash_cgi/apache_bash_cgi.pp, modules/services/unix/http/apache_bash_cgi/files/test.cgi, modules/services/unix/http/apache_bash_cgi/manifests/init.pp, modules/services/unix/http/apache_bash_cgi/secgen_metadata.xml, modules/vulnerabilities/unix/bash/shellshock/manifests/install.pp, modules/vulnerabilities/unix/bash/shellshock/secgen_metadata.xml, modules/vulnerabilities/unix/bash/shellshock/shellshock.pp, scenarios/simple_examples/shellshock_apache_vulnerability.xml, scenarios/simple_examples/shellshock_vulnerability.xml
New scenario combines the two modules & is exploitable with metasploit module: exploit/multi/http/apache_mod_cgi_bash_env_exec
Installs GNU Bash 4.1 from source
Tested using the [bashcheck](github.com/hannob/bashcheck) tool after installation.
Hosts a bash script, test.cgi, on an apache server to demonstrate the remote exploitation of the shellshock vulnerability.
Cheers!
=> Vulnerability: Shellshock in bash

modules/utilities/unix/scanners/nmap/manifests/install.pp, modules/utilities/unix/scanners/nmap/nmap.pp, modules/utilities/unix/scanners/nmap/secgen_metadata.xml, modules/vulnerabilities/unix/local/setuid_nmap/manifests/init.pp, modules/vulnerabilities/unix/local/setuid_nmap/secgen_metadata.xml, modules/vulnerabilities/unix/local/setuid_nmap/setuid_nmap.pp, scenarios/simple_examples/setuid_nmap_escalation_vulnerability.xml
In order to demonstrate the privilege escalation the scenario contains a remote user level vulnerability as well as setuid_nmap. 
We can use metasploit to exploit our remote user level vulnerability (exploits/unix/misc/distcc_exec - distcc_exec was selected in this example), upgrade our shell to meterpreter (post/multi/manage/shell_to_meterpreter) and then escalate to root (exploit/unix/local/setuid_nmap).
First step is getting onto the box as a non-root user. I use the -j flag on the exploit command to send the session into the background.
use exploit/unix/misc/distcc_exec
set RHOST 192.168.0.13
exploit -j
The setuid_nmap exploit requires a meterpreter session for use. Due to the distcc_exec module design we cannot use a meterpreter payload so we're given a standard shell. We can use the …
=> Vulnerability: Nmap setuid local privilege escalation

lib/objects/local_string_encoder.rb, modules/encoders/selector/random_string_selector/secgen_local/local.rb, modules/encoders/selector/random_string_selector/secgen_metadata.xml, scenarios/parameterised_examples/encode_and_leak_multiple_values.xml, scenarios/parameterised_examples/encoder_examples/random_selection.xml
A simple encoder module that can be used to provide random selection between inputs (for example, if you want to randomly select between potential parameter values).
Use in a scenario:
```xml
<vulnerability read_fact="strings_to_leak">
<input into="strings_to_leak">
<encoder type="string_selector">
<input into="strings_to_encode">
<generator/>
<generator/>
<value>Nothing to see here move along...</value>
</input>
</encoder>
</input>
</vulnerability>
```
=> random selection between inputs

modules/services/unix/ftp/proftpd/manifests/configure.pp, modules/services/unix/ftp/proftpd/manifests/init.pp, modules/services/unix/ftp/proftpd/manifests/install.pp, modules/services/unix/ftp/proftpd/manifests/service.pp, modules/services/unix/ftp/proftpd/proftpd.pp, modules/services/unix/ftp/proftpd/secgen_metadata.xml, modules/services/unix/ftp/proftpd/templates/proftpd.erb, scenarios/simple_examples/proftpd_service.xml
Simple service module for ProFTPd.
ProFTPd uses PAM for authentication and has root FTP access disabled, so you may need to create a user on the VM to test.
Cheers,
Tom
=> Service: ProFTPd

lib/readers/module_reader.rb
This fixes #91 
@thomashaw, could you please do a quick test for me to check that the default inputs are behaving as expected, for example build the project for the team project and CTF scenarios and just check that the encoded outputs all look sane. Thanks!
=> fixed issue with passing a nested literal value into a default module input

README.md, lib/helpers/constants.rb, lib/output/project_files_creator.rb, lib/schemas/base_metadata_schema.xsd, lib/schemas/vulnerability_metadata_schema.xsd, lib/templates/Vagrantfile.erb, modules/bases/windows_server_2008_r2_amd64/Autounattend.xml.erb, modules/bases/windows_server_2008_r2_amd64/Packerfile.erb, modules/bases/windows_server_2008_r2_amd64/puppet_install/LICENSE, modules/bases/windows_server_2008_r2_amd64/puppet_install/windows.ps1, modules/bases/windows_server_2008_r2_amd64/secgen_metadata.xml, modules/bases/windows_server_2008_r2_amd64/virtualbox_guest_install/windows.bat, scenarios/windows_scenario.xml
Will download ISO from microsoft site, will then build basebox (storing in VAGRANT_BASEBOX_STORAGE) and will then build with vagrant.
If Basebox is not present SecGen will prompt whether to use packer (requires download from packer website in README.md and for the binary to be in the system path) to build the Basebox.
*** Changes ***
constants.rb
51-57: Added the 2 constants PUPPET_VERSION: version of puppet to install on the newly generated system, and VAGRANT_BASEBOX_STORAGE which stores generated baseboxes (currently set to SecGen_root/.generated).
project_files_creator.rb
48-80: Added logic to check for existing basebox and to generate new basebox if not present.
base_metadata_schema.xsd
11: Added windows to platform options type
45-50: Added extra packer helper tags, packerfile_path …
=> Adds the Windows 2008 r2 server 64 bit basebox, allows for no license.

lib/output/project_files_creator.rb
Leaving the uploads folder causes the import to fail in CTFd.
=> Fix issue with uploads folder

modules/generators/structured_content/hackerbot_config/hb_access_controls/templates/access_controls.md.erb, modules/generators/structured_content/hackerbot_config/hb_containers/templates/containers.md.erb, modules/generators/structured_content/hackerbot_config/hb_containers/templates/intro.md.erb
Hi @cliffe,
I've made some changes to the ADS/PDS labsheets for the access controls and containers labs. Let me know what you think.
Most are minor updates, but I've added another step to the access controls lab that requires the students to investigate the directory level permissions. The directory level permissions are set to `rwx --- ---`, so the file read attempt on line 215 would always be denied, even if the file perms were set to a+r.
Cheers,
Tom
=> ADS/PDS: Labsheet changes

modules/vulnerabilities/unix/webapp/onlinestore/manifests/install.pp
=> Fix comparison operator typos

lib/batch/batch_secgen.rb
When copying flags, scenario, and log file, create back up project folder if not exist.
If the folder does not exist, Fileutil.cp can not copy file, Fileutil.cp through exception.
-----
How to produce this error:
$ ruby lib/batch/batch_secgen.rb add --instances tom,cliffe --- run
$ ruby lib/batch/batch_secgen.rb start
Summary of Error:
```
batch_secgen.rb:241:in `block in start'
fileutils.rb:1386:in `initialize': No such file or directory
```
=> Bug fix: create back up folder if not exist

modules/generators/html/vuln_snippets/xss_search_template/secgen_local/local.rb
Implementation improved using regex instead of a hardcoded list of payloads. Most common usages of script tags will work and grant the flag, e.g. `<script>alert(document.cookie);</script>`. Best when used at "easy" level, i.e. without blacklisting keywords. 
This is an easy flag which most students should get straight away. There are still holes in the implementation, but these should hopefully remain unnoticed if students "find the flag and move on". 
If a purely flag-based method of scoring is to be used, this release should also contain more difficult challenges, possibly as part of #197 .
=> Improved code to grant XSS flag - fixes Issue #196.

modules/vulnerabilities/unix/misc/jboss/files/jboss.service, modules/vulnerabilities/unix/misc/jboss/jboss.pp, modules/vulnerabilities/unix/misc/jboss/manifests/flags.pp, modules/vulnerabilities/unix/misc/jboss/manifests/install.pp, modules/vulnerabilities/unix/misc/jboss/secgen_metadata.xml
Tested and confirmed exploitable using local LXC containers, instead of Hacktivity VMs because of problems with Hacktivity. Shouldn't be a problem but good to know anyway.
=> add module jboss

modules/vulnerabilities/unix/http/apache_druid_rce/files/stretch.list, modules/vulnerabilities/unix/http/jenkins_cli/files/stretch.list
Recent changes to debian repositories, mean stretch is being archived from this point on. These updates reflect those changes.
=> change repos to use debian archive

modules/vulnerabilities/unix/web_training/security_shepherd/templates/coreSchema.sql.erb
Fixes the class generation so that the year is dynamic. Current behaviour hardcodes 'wns' which is apparently invalid within Shepherd as it requires a year. 
This also adds an additional SQL statement so that the class is automatically assigned to all users, even during registration.
=> Shepherd class updates
