cliffe/SecGen

secgen.rb

merge correction, re-added emilia's welcome + licence information changes

Welcome + licence details  (merge correction)

---

config/scenario.xml
lib/configuration.rb
lib/constants.rb
lib/helpers/vulnerability_helper.rb
lib/helpers/vulnerability_processor.rb
lib/managers/base_manager.rb
lib/managers/network_manager.rb
lib/managers/service_manager.rb
lib/objects/base_box.rb
lib/objects/base_module.rb
lib/objects/network.rb
lib/objects/service.rb
lib/objects/site.rb
lib/objects/system.rb
lib/objects/vulnerability.rb
lib/systemreader.rb
lib/templates/report.erb
lib/templates/vagrantbase.erb
lib/xml_report_generator.rb
tests/helper_tests/vulnerability_processor_tests.rb
xml/bases.xml

Changed Object variables to Object attributes hashes

Changed Object variables to Object attributes hashes

---

Gemfile
Gemfile.lock
documentation/yard/rakefile.rb
lib/readers/system_reader.rb

Post update fixes

---

modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/files/proftpd.init.d
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/manifests/config.pp
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/manifests/install.pp
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/manifests/service.pp
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/proftpd_133c_backdoor.pp
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/secgen_metadata.xml
modules/vulnerabilities/unix/ftp/proftpd_133c_backdoor/templates/proftpd.erb
scenarios/simple_examples/proftpd_133c_backdoor_vulnerability.xml

Installed from source tarball for now until the OBS stuff is figured out.
Cheers!

Vulnerability: ProFTPd 1.3.3c backdoor

---

modules/services/unix/firewall/firewall/firewall.pp
modules/services/unix/firewall/firewall/secgen_metadata.xml
scenarios/simple_examples/firewall_configuration_example.xml

@Jjk422 I've merged your firewall module and made a couple of minor changes, here's an example of a way I think we should handle the module dependency issue for now. 
I've removed the duplicate puppet code from the module and included the dependent module in the example scenario and left a TODO, this way when we get to implementing the dependency handling we won't have to hunt for duplicate code that needs removing.
Cheers,
Tom

Firewall merge small changes to demonstrate scenario creation pre-dependencies.

---

modules/services/unix/ftp/vsftpd/LICENSE
modules/services/unix/ftp/vsftpd/README.md
modules/services/unix/ftp/vsftpd/Rakefile
modules/services/unix/ftp/vsftpd/checksums.json
modules/services/unix/ftp/vsftpd/files/chroot_list
modules/services/unix/ftp/vsftpd/files/user_list
modules/services/unix/ftp/vsftpd/lib/facter/vsftpd_installed_version.rb
modules/services/unix/ftp/vsftpd/manifests/init.pp
modules/services/unix/ftp/vsftpd/manifests/params.pp
modules/services/unix/ftp/vsftpd/manifests/spec.pp
modules/services/unix/ftp/vsftpd/metadata.json
modules/services/unix/ftp/vsftpd/secgen_metadata.xml
modules/services/unix/ftp/vsftpd/spec/classes/vsftpd_spec.rb
modules/services/unix/ftp/vsftpd/spec/spec_helper.rb
modules/services/unix/ftp/vsftpd/templates/spec.erb
modules/services/unix/ftp/vsftpd/templates/vsftpd.conf.erb
modules/services/unix/ftp/vsftpd/vsftpd.pp
scenarios/simple_examples/vsftpd_service.xml

Login currently is via username:user and password:user. Has 2 test files and one test directory, shouldn't be able to log in as root or access root files .e.g '/etc/shadow'.

Secure vsftpd module

---

modules/vulnerabilities/unix/access_control_misconfigurations/uid_less_root/manifests/change_uid_permissions.pp
modules/vulnerabilities/unix/access_control_misconfigurations/uid_less_root/secgen_metadata.xml
modules/vulnerabilities/unix/access_control_misconfigurations/uid_less_root/uid_less_root.pp
scenarios/simple_examples/access_control_misconfigurations_uid_less_root.xml

Access_control_misconfigurations_uid_less_root.xml can be used to test.
Should be able to read any file from any user account with less.

Access control vulnerability, allows less to run as root for any user.

---

secgen.rb

Added command line option to list all SecGen scenarios in the scenarios directory.
Command line option is 'list-scenarios'.

List all SecGen scenarios

---

modules/utilities/unix/smb/smbclient/manifests/install.pp
modules/utilities/unix/smb/smbclient/secgen_metadata.xml
modules/utilities/unix/smb/smbclient/smbclient.pp
scenarios/simple_examples/smbclient_utility.xml

Scenario file found at '/home/user/RubymineProjects/SecGen/scenarios/simple_examples/smbclient_utility.xml'
Installs smbclient for use with samba services.

Smbclient utility module.

---

modules/networks/public/public_network_2/secgen_metadata.xml

Added public network with a specified static IP range.

Create public_network_2 secgen_metadata.xml

---

lib/output/project_files_creator.rb
lib/templates/Vagrantfile.erb
modules/bases/windows_server_2008_r2_amd64/Packerfile.erb
modules/bases/windows_server_2008_r2_amd64/scripts/vm-guest-tools.bat
modules/bases/windows_server_2008_r2_amd64/secgen_metadata.xml
secgen.rb

This should complement #138. It also cleans up provider guest tools from Windows after installation.

Fix windows image not built properly for ESXi

---

.gitignore
modules/vulnerabilities/unix/webapp/commando/manifests/install.pp
modules/vulnerabilities/unix/webapp/commando/templates/logout.php.erb
modules/vulnerabilities/unix/webapp/commando/templates/profile.php.erb
modules/vulnerabilities/unix/webapp/commando/templates/subtemplates/nav.html.erb
modules/vulnerabilities/unix/webapp/commando/templates/update_profile.php.erb
scenarios/security_audit/rand_webapp.xml

Some small improvements. Created a new page to allow logged-in users to update their profile. Fixed log out functionality. CSRF should now be possible.

Commando csrf

---

modules/vulnerabilities/unix/webapp/commando/files/css/index.css
modules/vulnerabilities/unix/webapp/commando/manifests/install.pp
modules/vulnerabilities/unix/webapp/commando/secgen_metadata.xml

Removed redundant flag. Fixes #208.

Commando redundant flag

---

modules/vulnerabilities/unix/email_phishing/phish_victim_bot/files/MailReaderTest.java

These tests need JUnit5 and Mockito 4.0 in order to run. At the moment, we are simply downloading the JARs from the internet and making them available on the classpath.

Added some unit tests to MailReader class.

---

scenarios/labs/workshops/induction.xml

Fixed small inaccuracy in orientation clue.

---

README.md
lib/templates/Vagrantfile.erb
secgen.rb

I fixed the issues with the vagrant file using ESXI plugin. 
I also updated the readme.md to reflect the changes.

Fixed ESXI Vagrant File

---

modules/services/unix/http/apache_stretch_compatible/apache/secgen_metadata.xml

Whilst testing exploit modules, issues arose when using the apache module with additional services. 
Commit related is: 158283d
@thomashaw provided the following, which fixed the issues. 
Most line changes here are just IDE related formatting. The key lines are:
`  <conflict>
<name>bases/.*kali.*</name>
</conflict>`

Apache base fix

---

lib/objects/local_string_generator.rb
lib/resources/linelists/top_50_sudo_commands
lib/resources/linelists/top_90_linux_commands
modules/generators/content/bash_history/secgen_local/local.rb
modules/generators/content/bash_history/secgen_metadata.xml
modules/generators/content/bash_history/templates/bash_history.md.erb

PR to add bash_history generator

Bash History File Generator

---

modules/vulnerabilities/unix/http/lucee_rce/secgen_metadata.xml
scenarios/ctf/disasterous_development.xml

New CTF Scenario for lucee_rce. 
Also adds the msf_module tag containing relevant msf path.

Lucee_rce CTF Scenario and msf Module for exploit

---

scenarios/ctf/administration_woes.xml
scenarios/ctf/catching_sparks.xml
scenarios/ctf/erlang_explosion.xml
scenarios/ctf/eventful_data.xml
scenarios/ctf/manage_this.xml

Ill Close the other PR. 
Contains scenarios for:
- Apache Spark
- Apache Druid
- Apache Couchdb
- Jenkins
-  GLPI

CTF Scenarios

---

modules/generators/messages/randsom_note/secgen_local/local.rb
modules/generators/messages/randsom_note/secgen_metadata.xml
modules/generators/messages/randsom_note/templates/ransom_note.md.erb

new file:   modules/generators/messages/randsom_note/secgen_local/local.rb
new file:   modules/generators/messages/randsom_note/secgen_metadata.xml
new file:   modules/generators/messages/randsom_note/templates/ransom_note.md.erb
Initial Push for Ransom Note

	new file:   modules/generators/messages/randsom_note/ransom_note.pp

---

modules/generators/config_files/filezilla_config/secgen_local/local.rb
modules/generators/config_files/filezilla_config/secgen_metadata.xml
modules/generators/config_files/filezilla_config/templates/filezilla_config.xml.erb

Filezilla Config File Generator

---

modules/generators/content/password_file/secgen_metadata.xml
modules/generators/content/password_file/templates/password_file.md.erb

Passwordlist

---

modules/generators/structured_content/ss_modules/secgen_local/local.rb
modules/vulnerabilities/unix/web_training/security_shepherd/manifests/install.pp
modules/vulnerabilities/unix/web_training/security_shepherd/manifests/mariadb.pp
modules/vulnerabilities/unix/web_training/security_shepherd/templates/coreSchema.sql.erb
scenarios/labs/web_network_security/WNS_1.xml
scenarios/labs/web_network_security/WNS_2.xml
scenarios/labs/web_network_security/WNS_3.xml
scenarios/labs/web_network_security/WNS_4.xml
scenarios/labs/web_network_security/WNS_5.xml
scenarios/labs/web_network_security/WNS_6.xml
scenarios/labs/web_network_security/WNS_8.xml

Here is the initial commit for the Web and Network security scenarios. It includes:
- Changes to the initial shepherd install process
- Changes to the ss_modules generator filter process
- WNS scenarios 1-8
Changes have been tested internally and seem to deploy correctly.

Web network security Scenarios

---

modules/vulnerabilities/unix/web_training/security_shepherd/manifests/install.pp
modules/vulnerabilities/unix/web_training/security_shepherd/manifests/mariadb.pp
modules/vulnerabilities/unix/web_training/security_shepherd/templates/coreSchema.sql.erb
scenarios/labs/web_security/1_intro_web_security.xml
scenarios/labs/web_security/2_sessions_and_cookies.xml
scenarios/labs/web_security/3_xss.xml
scenarios/labs/web_security/4_sqli.xml
scenarios/labs/web_security/5_sqli_advanced.xml
scenarios/labs/web_security/6_csrf.xml
scenarios/labs/web_security/7_additional_web.xml

Updates as discussed. New install process.

Web network security

---

modules/vulnerabilities/unix/web_training/security_shepherd/templates/coreSchema.sql.erb

open registration and prevent initial password change

Security Shepherd open registration and prevention of initial password change on user

---

modules/utilities/windows/adobereader/adobereader.pp
modules/utilities/windows/adobereader/manifests/install.pp
modules/utilities/windows/adobereader/secgen_metadata.xml
modules/utilities/windows/keepass/keepass.pp
modules/utilities/windows/keepass/manifests/config.pp
modules/utilities/windows/keepass/manifests/install.pp
modules/utilities/windows/keepass/secgen_metadata.xml
modules/utilities/windows/msft_tools/procexp/manifests/install.pp
modules/utilities/windows/msft_tools/procexp/procexp.pp
modules/utilities/windows/msft_tools/procexp/secgen_metadata.xml
modules/utilities/windows/msft_tools/procmon/manifests/install.pp
modules/utilities/windows/msft_tools/procmon/procmon.pp
modules/utilities/windows/msft_tools/procmon/secgen_metadata.xml
modules/utilities/windows/netcat/manifests/install.pp
modules/utilities/windows/netcat/netcat.pp
modules/utilities/windows/netcat/secgen_metadata.xml
modules/utilities/windows/nginx/manifests/install.pp
modules/utilities/windows/nginx/nginx.pp
modules/utilities/windows/nginx/secgen_metadata.xml
modules/utilities/windows/notepadplusplus/manifests/install.pp
modules/utilities/windows/notepadplusplus/notepadplusplus.pp
modules/utilities/windows/notepadplusplus/secgen_metadata.xml
modules/utilities/windows/vlc/manifests/install.pp
modules/utilities/windows/vlc/secgen_metadata.xml
modules/utilities/windows/vlc/vlc.pp

Add the following windows utilities:
- Adobe Reader
- Keepass
- Netcat (This differs to the one existing as this pulls from chocolatey)
- Nginx
- VLC
- Notepad++
- Microsoft Tools:
- Procmon (Process Monitor)
- Procexp (Process Explorer)

Add multiple windows utilities
